### ISSUE TITLE
Change the cycle duration of partners carousel.

### ISSUE THREAD

**Issue by nawazishali** [fcckarachi/fcckarachi.github.io#15]
The partners carousel is currently rotating at 1 sec interval, change it to 2.5 secs to make it look good and responsive to user actions.

Read our [contributing guide](https://github.com/fcckarachi/fcckarachi.github.io/blob/develop/CONTRIBUTING.md) thoroughly before going forward with the issue.

Feel free to ask any questions regarding the issue in the comments below.

**Comment by hass321** [comment]
interested to contribute.

**Comment by nawazishali** [comment]
OK Follow our contribution guide and join the organization so that I can assign this to you.
