### ISSUE TITLE
Add BlackFire Host Logo as our Sponsor/Partner.

### ISSUE THREAD

**Issue by nawazishali** [fcckarachi/fcckarachi.github.io#8]
We need to add Black fire host logo as our sponsor. Please make sure you download the logo from the given link and place in the right folder. 

Logo Link: https://blackfirehost.com/templates/hostify/img/android-icon-192x192.png
Website Url: https://blackfirehost.com/index.php

Please read [Contributing Document](https://github.com/fcckarachi/fcckarachi.github.io/blob/develop/CONTRIBUTING.md) so that we can follow best practices.

**Comment by Ali-Khan5** [comment]
i am working on this issue ...
